src/java/model/CampaignData.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author alex
 */
@Entity
@Table(name = "campaign_data")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "CampaignData.findAll", query = "SELECT c FROM CampaignData c"),
    @NamedQuery(name = "CampaignData.findByCampaignDataId", query = "SELECT c FROM CampaignData c WHERE c.campaignDataId = :campaignDataId"),
    @NamedQuery(name = "CampaignData.findByNoWeek", query = "SELECT c FROM CampaignData c WHERE c.noWeek = :noWeek"),
    @NamedQuery(name = "CampaignData.findByWeekDescr", query = "SELECT c FROM CampaignData c WHERE c.weekDescr = :weekDescr"),
    @NamedQuery(name = "CampaignData.findByMedium", query = "SELECT c FROM CampaignData c WHERE c.medium = :medium"),
    @NamedQuery(name = "CampaignData.findByAdType", query = "SELECT c FROM CampaignData c WHERE c.adType = :adType"),
    @NamedQuery(name = "CampaignData.findByCountry", query = "SELECT c FROM CampaignData c WHERE c.country = :country"),
    @NamedQuery(name = "CampaignData.findByImpressions", query = "SELECT c FROM CampaignData c WHERE c.impressions = :impressions"),
    @NamedQuery(name = "CampaignData.findByClicks", query = "SELECT c FROM CampaignData c WHERE c.clicks = :clicks"),
    @NamedQuery(name = "CampaignData.findByCost", query = "SELECT c FROM CampaignData c WHERE c.cost = :cost")})
public class CampaignData implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "campaign_data_id", nullable = false)
    private Integer campaignDataId;
    @Basic(optional = false)
    @NotNull
    @Column(name = "no_week", nullable = false)
    private int noWeek;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "week_descr", nullable = false, length = 255)
    private String weekDescr;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "medium", nullable = false, length = 255)
    private String medium;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "ad_type", nullable = false, length = 255)
    private String adType;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 100)
    @Column(name = "country", nullable = false, length = 100)
    private String country;
    @Basic(optional = false)
    @NotNull
    @Column(name = "impressions", nullable = false)
    private int impressions;
    @Basic(optional = false)
    @NotNull
    @Column(name = "clicks", nullable = false)
    private int clicks;
    @Basic(optional = false)
    @NotNull
    @Column(name = "cost", nullable = false)
    private double cost;
    @JoinColumn(name = "campaign_id", referencedColumnName = "campaign_id", nullable = false)
    @ManyToOne(optional = false)
    private Campaign campaignId;

    public CampaignData() {
    }

    public CampaignData(Integer campaignDataId) {
        this.campaignDataId = campaignDataId;
    }

    public CampaignData(Integer campaignDataId, int noWeek, String weekDescr, String medium, String adType, String country, int impressions, int clicks, double cost) {
        this.campaignDataId = campaignDataId;
        this.noWeek = noWeek;
        this.weekDescr = weekDescr;
        this.medium = medium;
        this.adType = adType;
        this.country = country;
        this.impressions = impressions;
        this.clicks = clicks;
        this.cost = cost;
    }

    public Integer getCampaignDataId() {
        return campaignDataId;
    }

    public void setCampaignDataId(Integer campaignDataId) {
        this.campaignDataId = campaignDataId;
    }

    public int getNoWeek() {
        return noWeek;
    }

    public void setNoWeek(int noWeek) {
        this.noWeek = noWeek;
    }

    public String getWeekDescr() {
        return weekDescr;
    }

    public void setWeekDescr(String weekDescr) {
        this.weekDescr = weekDescr;
    }

    public String getMedium() {
        return medium;
    }

    public void setMedium(String medium) {
        this.medium = medium;
    }

    public String getAdType() {
        return adType;
    }

    public void setAdType(String adType) {
        this.adType = adType;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public int getImpressions() {
        return impressions;
    }

    public void setImpressions(int impressions) {
        this.impressions = impressions;
    }

    public int getClicks() {
        return clicks;
    }

    public void setClicks(int clicks) {
        this.clicks = clicks;
    }

    public double getCost() {
        return cost;
    }

    public void setCost(double cost) {
        this.cost = cost;
    }

    public Campaign getCampaignId() {
        return campaignId;
    }

    public void setCampaignId(Campaign campaignId) {
        this.campaignId = campaignId;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (campaignDataId != null ? campaignDataId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof CampaignData)) {
            return false;
        }
        CampaignData other = (CampaignData) object;
        if ((this.campaignDataId == null && other.campaignDataId != null) || (this.campaignDataId != null && !this.campaignDataId.equals(other.campaignDataId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "model.CampaignData[ campaignDataId=" + campaignDataId + " ]";
    }
    
}

src/java/controller/CampaignDataController.java
package controller;

import model.CampaignData;
import controller.util.JsfUtil;
import controller.util.PaginationHelper;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("campaignDataController")
@SessionScoped
public class CampaignDataController implements Serializable {

    private CampaignData current;
    private DataModel items = null;
    @EJB
    private controller.CampaignDataFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public CampaignDataController() {
    }

    public CampaignData getSelected() {
        if (current == null) {
            current = new CampaignData();
            selectedItemIndex = -1;
        }
        return current;
    }

    private CampaignDataFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (CampaignData) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new CampaignData();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("web.Bundle").getString("CampaignDataCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("web.Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (CampaignData) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("web.Bundle").getString("CampaignDataUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("web.Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (CampaignData) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("web.Bundle").getString("CampaignDataDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("web.Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public CampaignData getCampaignData(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = CampaignData.class)
    public static class CampaignDataControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            CampaignDataController controller = (CampaignDataController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "campaignDataController");
            return controller.getCampaignData(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof CampaignData) {
                CampaignData o = (CampaignData) object;
                return getStringKey(o.getCampaignDataId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + CampaignData.class.getName());
            }
        }

    }

}

web/campaignData/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateCampaignDataTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateCampaignDataLabel_campaignDataId}" for="campaignDataId" />
                    <h:inputText id="campaignDataId" value="#{campaignDataController.selected.campaignDataId}" title="#{bundle.CreateCampaignDataTitle_campaignDataId}" required="true" requiredMessage="#{bundle.CreateCampaignDataRequiredMessage_campaignDataId}"/>
                    <h:outputLabel value="#{bundle.CreateCampaignDataLabel_noWeek}" for="noWeek" />
                    <h:inputText id="noWeek" value="#{campaignDataController.selected.noWeek}" title="#{bundle.CreateCampaignDataTitle_noWeek}" required="true" requiredMessage="#{bundle.CreateCampaignDataRequiredMessage_noWeek}"/>
                    <h:outputLabel value="#{bundle.CreateCampaignDataLabel_weekDescr}" for="weekDescr" />
                    <h:inputText id="weekDescr" value="#{campaignDataController.selected.weekDescr}" title="#{bundle.CreateCampaignDataTitle_weekDescr}" required="true" requiredMessage="#{bundle.CreateCampaignDataRequiredMessage_weekDescr}"/>
                    <h:outputLabel value="#{bundle.CreateCampaignDataLabel_medium}" for="medium" />
                    <h:inputText id="medium" value="#{campaignDataController.selected.medium}" title="#{bundle.CreateCampaignDataTitle_medium}" required="true" requiredMessage="#{bundle.CreateCampaignDataRequiredMessage_medium}"/>
                    <h:outputLabel value="#{bundle.CreateCampaignDataLabel_adType}" for="adType" />
                    <h:inputText id="adType" value="#{campaignDataController.selected.adType}" title="#{bundle.CreateCampaignDataTitle_adType}" required="true" requiredMessage="#{bundle.CreateCampaignDataRequiredMessage_adType}"/>
                    <h:outputLabel value="#{bundle.CreateCampaignDataLabel_country}" for="country" />
                    <h:inputText id="country" value="#{campaignDataController.selected.country}" title="#{bundle.CreateCampaignDataTitle_country}" required="true" requiredMessage="#{bundle.CreateCampaignDataRequiredMessage_country}"/>
                    <h:outputLabel value="#{bundle.CreateCampaignDataLabel_impressions}" for="impressions" />
                    <h:inputText id="impressions" value="#{campaignDataController.selected.impressions}" title="#{bundle.CreateCampaignDataTitle_impressions}" required="true" requiredMessage="#{bundle.CreateCampaignDataRequiredMessage_impressions}"/>
                    <h:outputLabel value="#{bundle.CreateCampaignDataLabel_clicks}" for="clicks" />
                    <h:inputText id="clicks" value="#{campaignDataController.selected.clicks}" title="#{bundle.CreateCampaignDataTitle_clicks}" required="true" requiredMessage="#{bundle.CreateCampaignDataRequiredMessage_clicks}"/>
                    <h:outputLabel value="#{bundle.CreateCampaignDataLabel_cost}" for="cost" />
                    <h:inputText id="cost" value="#{campaignDataController.selected.cost}" title="#{bundle.CreateCampaignDataTitle_cost}" required="true" requiredMessage="#{bundle.CreateCampaignDataRequiredMessage_cost}"/>
                    <h:outputLabel value="#{bundle.CreateCampaignDataLabel_campaignId}" for="campaignId" />
                    <h:selectOneMenu id="campaignId" value="#{campaignDataController.selected.campaignId}" title="#{bundle.CreateCampaignDataTitle_campaignId}" required="true" requiredMessage="#{bundle.CreateCampaignDataRequiredMessage_campaignId}">
                        <f:selectItems value="#{campaignController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{campaignDataController.create}" value="#{bundle.CreateCampaignDataSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{campaignDataController.prepareList}" value="#{bundle.CreateCampaignDataShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateCampaignDataIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/campaignData/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditCampaignDataTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditCampaignDataLabel_campaignDataId}" for="campaignDataId" />
                    <h:inputText id="campaignDataId" value="#{campaignDataController.selected.campaignDataId}" title="#{bundle.EditCampaignDataTitle_campaignDataId}" required="true" requiredMessage="#{bundle.EditCampaignDataRequiredMessage_campaignDataId}"/>
                    <h:outputLabel value="#{bundle.EditCampaignDataLabel_noWeek}" for="noWeek" />
                    <h:inputText id="noWeek" value="#{campaignDataController.selected.noWeek}" title="#{bundle.EditCampaignDataTitle_noWeek}" required="true" requiredMessage="#{bundle.EditCampaignDataRequiredMessage_noWeek}"/>
                    <h:outputLabel value="#{bundle.EditCampaignDataLabel_weekDescr}" for="weekDescr" />
                    <h:inputText id="weekDescr" value="#{campaignDataController.selected.weekDescr}" title="#{bundle.EditCampaignDataTitle_weekDescr}" required="true" requiredMessage="#{bundle.EditCampaignDataRequiredMessage_weekDescr}"/>
                    <h:outputLabel value="#{bundle.EditCampaignDataLabel_medium}" for="medium" />
                    <h:inputText id="medium" value="#{campaignDataController.selected.medium}" title="#{bundle.EditCampaignDataTitle_medium}" required="true" requiredMessage="#{bundle.EditCampaignDataRequiredMessage_medium}"/>
                    <h:outputLabel value="#{bundle.EditCampaignDataLabel_adType}" for="adType" />
                    <h:inputText id="adType" value="#{campaignDataController.selected.adType}" title="#{bundle.EditCampaignDataTitle_adType}" required="true" requiredMessage="#{bundle.EditCampaignDataRequiredMessage_adType}"/>
                    <h:outputLabel value="#{bundle.EditCampaignDataLabel_country}" for="country" />
                    <h:inputText id="country" value="#{campaignDataController.selected.country}" title="#{bundle.EditCampaignDataTitle_country}" required="true" requiredMessage="#{bundle.EditCampaignDataRequiredMessage_country}"/>
                    <h:outputLabel value="#{bundle.EditCampaignDataLabel_impressions}" for="impressions" />
                    <h:inputText id="impressions" value="#{campaignDataController.selected.impressions}" title="#{bundle.EditCampaignDataTitle_impressions}" required="true" requiredMessage="#{bundle.EditCampaignDataRequiredMessage_impressions}"/>
                    <h:outputLabel value="#{bundle.EditCampaignDataLabel_clicks}" for="clicks" />
                    <h:inputText id="clicks" value="#{campaignDataController.selected.clicks}" title="#{bundle.EditCampaignDataTitle_clicks}" required="true" requiredMessage="#{bundle.EditCampaignDataRequiredMessage_clicks}"/>
                    <h:outputLabel value="#{bundle.EditCampaignDataLabel_cost}" for="cost" />
                    <h:inputText id="cost" value="#{campaignDataController.selected.cost}" title="#{bundle.EditCampaignDataTitle_cost}" required="true" requiredMessage="#{bundle.EditCampaignDataRequiredMessage_cost}"/>
                    <h:outputLabel value="#{bundle.EditCampaignDataLabel_campaignId}" for="campaignId" />
                    <h:selectOneMenu id="campaignId" value="#{campaignDataController.selected.campaignId}" title="#{bundle.EditCampaignDataTitle_campaignId}" required="true" requiredMessage="#{bundle.EditCampaignDataRequiredMessage_campaignId}">
                        <f:selectItems value="#{campaignController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{campaignDataController.update}" value="#{bundle.EditCampaignDataSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditCampaignDataViewLink}"/>
                <br />
                <h:commandLink action="#{campaignDataController.prepareList}" value="#{bundle.EditCampaignDataShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditCampaignDataIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/campaignData/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListCampaignDataTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListCampaignDataEmpty}" rendered="#{campaignDataController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{campaignDataController.items.rowCount > 0}">
                    <h:outputText value="#{campaignDataController.pagination.pageFirstItem + 1}..#{campaignDataController.pagination.pageLastItem + 1}/#{campaignDataController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{campaignDataController.previous}" value="#{bundle.Previous} #{campaignDataController.pagination.pageSize}" rendered="#{campaignDataController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{campaignDataController.next}" value="#{bundle.Next} #{campaignDataController.pagination.pageSize}" rendered="#{campaignDataController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{campaignDataController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCampaignDataTitle_campaignDataId}"/>
                            </f:facet>
                            <h:outputText value="#{item.campaignDataId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCampaignDataTitle_noWeek}"/>
                            </f:facet>
                            <h:outputText value="#{item.noWeek}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCampaignDataTitle_weekDescr}"/>
                            </f:facet>
                            <h:outputText value="#{item.weekDescr}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCampaignDataTitle_medium}"/>
                            </f:facet>
                            <h:outputText value="#{item.medium}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCampaignDataTitle_adType}"/>
                            </f:facet>
                            <h:outputText value="#{item.adType}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCampaignDataTitle_country}"/>
                            </f:facet>
                            <h:outputText value="#{item.country}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCampaignDataTitle_impressions}"/>
                            </f:facet>
                            <h:outputText value="#{item.impressions}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCampaignDataTitle_clicks}"/>
                            </f:facet>
                            <h:outputText value="#{item.clicks}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCampaignDataTitle_cost}"/>
                            </f:facet>
                            <h:outputText value="#{item.cost}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCampaignDataTitle_campaignId}"/>
                            </f:facet>
                            <h:outputText value="#{item.campaignId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{campaignDataController.prepareView}" value="#{bundle.ListCampaignDataViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{campaignDataController.prepareEdit}" value="#{bundle.ListCampaignDataEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{campaignDataController.destroy}" value="#{bundle.ListCampaignDataDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{campaignDataController.prepareCreate}" value="#{bundle.ListCampaignDataCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListCampaignDataIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>